# Generated by Django 5.0.3 on 2024-07-22 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0013_alter_visitrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='registrationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
